// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// systematic_resampling
arma::vec systematic_resampling(const arma::vec& normweights, int nparticles, double uniform);
RcppExport SEXP _GibbsFlow_systematic_resampling(SEXP normweightsSEXP, SEXP nparticlesSEXP, SEXP uniformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type normweights(normweightsSEXP);
    Rcpp::traits::input_parameter< int >::type nparticles(nparticlesSEXP);
    Rcpp::traits::input_parameter< double >::type uniform(uniformSEXP);
    rcpp_result_gen = Rcpp::wrap(systematic_resampling(normweights, nparticles, uniform));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GibbsFlow_systematic_resampling", (DL_FUNC) &_GibbsFlow_systematic_resampling, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GibbsFlow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
