# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname systematic_resampling
#' @title Perform systematic resampling
#' @param normweights normalized particle weights 
#' @param nparticles number of particles
#' @param uniform uniform variable between 0 to 1 / nparticles 
#' @return \code{ancestors} ancestor indices
#' @export
systematic_resampling <- function(normweights, nparticles, uniform) {
    .Call('_GibbsFlow_systematic_resampling', PACKAGE = 'GibbsFlow', normweights, nparticles, uniform)
}

